---
title: "Summer"
output: 
  pdf_document: 
    fig_height: 8
    fig_width: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### load the corpus

```{r load, tidy=FALSE}
library(tm)
library(wordcloud)
library(ggplot2)
txt <- DirSource(directory = "../Data")
story.1st <- Corpus(txt)
story.raw.1st <- story.1st
story.1st <- tm_map(story.1st,  content_transformer(tolower))
story.1st <- tm_map(story.1st,  content_transformer(removePunctuation))
story.1st <- tm_map(story.1st,  content_transformer(removeNumbers))
story.1st <- tm_map(story.1st, removeWords, stopwords('english'))
SWList <-  c("summer", 
             "summers", 
             "todd", 
             "todds", 
             "wayne", 
             "waynes",
             "master",
             "masters",
             "sarah",
             "lisa",
             "mark",
             "justin",
             "boy",
             "boys",
             "man",
             "men",
             "williams",
             "william",
             "megan",
             "calvin",
             "marco",
             "marcos",
             "kevin",
             "bill",
             "black",
             "pink",
             "melanie",
             "english",
             "mike",
             "james",
             "steve",
             "teacher",
             "teachers",
             "will",
             "see",
             "now",
             "said",
             "began",
             "white",
             "red",
             "black",
             "woman",
             "women",
             "maria",
             "around",
             "knew",
             "gail",
             "can",
             "get",
             "felt",
             "hard",
             "well",
             "one",
             "two",
             "three",
             "four",
             "five",
             "six",
             "seven",
             "eight",
             "nine",
             "ten",
             "take",
             "right",
             "left",
             "sure",
             "asked",
             "continued",
             "husband",
             "shirley",
             "together",
             "barb",
             "done",
             "door",
             "face",
             "feel",
             "going",
             "just",
             "know",
             "let",
             "next",
             "noticed",
             "quickly",
             "reached",
             "sandy",
             "saw",
             "way",
             "without",
             "‘s",
             "air",
             "already",
             "became",
             "car",
             "coffee",
             "delvin",
             "enough",
             "gave",
             "heard",
             "high",
             "inch",
             "job",
             "long",
             "look",
             "marsha",
             "mind",
             "move",
             "ready",
             "realized",
             "really",
             "say",
             "started",
             "think",
             "try",
             "want",
             "watch",
             "watching",
             "room",
             "sgt",
             "drive",
             "blue",
             "onto",
             "thought",
             "give",
             "getting",
             "brought",
             "directly",
             "parking",
             "park",
             "clearly",
             "dan",
             "got",
             "lets",
             "let",
             "yet",
             "life",
             "replied",
             "reply",
             "life","came",
             "always",
             "knowing",
             "size",
             "top",
             "like",
             "many",
             "god",
             "may",
             "girl",
             "girls",
             "note",
             "long",
             "longer",
             "tell",
             "telling")
story.1st <- tm_map(story.1st, removeWords, SWList)


story.1st.copy <- story.1st
summary(story.1st)
#story.1st
#meta(story.1st[[1]])
```
### Analysis
```{r analysis, fig.width=11, fig.height=8, tidy=FALSE}
story.1st.stem  <- tm_map(story.1st, stemDocument)


myTdm.1st <- TermDocumentMatrix(story.1st, control=list(minWordLength = 1))
myTdm.1st
myTdm.1st.s <- TermDocumentMatrix(story.1st.stem, control=list(minWordLength = 1))
myTdm.1st.s


findFreqTerms(myTdm.1st, lowfreq = 10)
termFreq.1st <- rowSums(as.matrix(myTdm.1st))
termFreq.1st <- subset(termFreq.1st, termFreq.1st >=9)

#qplot(names(termFreq.1st), termFreq.1st, geom="bar",xlab="Terms")+coord_flip()
barplot(termFreq.1st, las=2)

m.1st <-as.matrix(myTdm.1st)
wordFreq.1st <- sort(rowSums(m.1st), decreasing=TRUE)
#set.seed(12345)
wordcloud(words=names(wordFreq.1st),
          freq = wordFreq.1st,
          min.freq=75,
          random.order = F)
```
now do it with stemmed and rebuild
```{r stem and re, fig.width=11, fig.height=8, tidy=FALSE}
story.comp.1st <- tm_map(story.1st.stem, stemCompletion, dictionary=story.1st.copy)

myTdm.comp.1st <- TermDocumentMatrix(story.comp.1st, control=list(minWordLength = 1))
myTdm.comp.1st

findFreqTerms(myTdm.comp.1st, lowfreq = 500)
termFreq.comp.1st <- rowSums(as.matrix(myTdm.comp.1st))
termFreq.comp.1st <- subset(termFreq.comp.1st, termFreq.comp >=500)

qplot(names(termFreq.comp.1st), termFreq.comp, geom="bar",xlab="Terms")+coord_flip()
barplot(termFreq.comp.1st, las=2)

m.comp.1st <- as.matrix(myTdm.comp.1st)
wordFreq.comp.1st <- sort(rowSums(m.comp.1st), decreasing=TRUE)
set.seed(12345)
wordcloud(words=names(wordFreq.comp.1st),
          freq = wordFreq.comp.1st,
          min.freq=20,
          random.order = F,
          rot.per = .1)
```
````
png(filename = "~/r/workspace/tm/image/camp.png", units="in", width=4,height=4, res=300)
````